### ISSUE TITLE
Is this program usable?

### ISSUE THREAD

**Issue by qnnnnez** [padillah/ScWorldEditor#5]
Hey @padillah , I downloaded the code and compiled it. However, after I opened a world, left area of the window turned into black with scrollbars, but nothing else happened. I am using Windows 10 with Visual Studio 2015.

**Comment by padillah** [comment]
No, it is not fully functional. I have not put a lot of time into it (as opposed to my other projects) because there has not been a lot of interest.

I do have the code in place to read the *.scworld file and hydrate the DirectoryEntries and Chunks, but that's where I left off.

If you would like to help I would love some suggestions or any input on making it work or making it better please feel free to contribute. Even the little interest you have shown is enough to make me think this should be dusted off and effort put into it.

And if you'd like to be a contributor, that would really be a huge help.

**Comment by qnnnnez** [comment]
I do have interest, but unfortunately, I had little time, either. And also, I am not a professional programmer and have no experience.
I will try to help, but I am not sure weather it helps. Anyway, there should be a useful world editor for Survivalcraft.
So far, the problem, I think, is the navigation. It is difficult to control as it is a 3D world.
